#ifndef DATATYPE_H
#define DATATYPE_H

enum ServerRequest {
    REQ_RAISECOM_LOGIN_USERNAME,
    REQ_RAISECOM_LOGIN_PASSWORD,
    REQ_CAP_LOGIN_USERNAME,
    REQ_CAP_LOGIN_PASSWORD,
    REQ_UNKNOWN
};

#endif // DATATYPE_H
